name: build-container

"on":
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            architecture: linux_amd64
            tag: latest
          - platform: linux/arm64
            architecture: linux_arm64
            tag: latest-arm64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            ARCHITECTURE=${{ matrix.architecture }}
          tags: |
            ghcr.io/tibeer/terraform-dyndns:${{ matrix.tag }}
